config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  
  def index
    @tasks = Task.all
  end
  
  def show
    
  end
  
  def new
    @task = Task.new
    
  end
  
  def create
    @task = Task.new(task_params)
    
    if @task.save
      flash[:success] = '正常に登録されました'
      redirect_to @task
    else
      flash.now[:danger] = '登録されませんでした'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @task.update(task_params)
      flash[:success] = '正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end
  
  
  def destroy
    @task.destroy

    flash[:success] = '正常に削除されました'
    redirect_to tasks_url
  end
  
  #共通部
  def set_task
    @task = Task.find(params[:id])
  end
  
  # Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <%= f.label :content, '買うもの入力' %>
  <%= f.text_field :content %>
  
  <%= f.label :status, '状況' %>
  <%= f.text_field :status %>
  
  <%= f.submit '登録' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>編集ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', task_path %>

app/views/tasks/index.html.erb
<h1>買うもの一覧</h1>

<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.id, task %> : <%= task.content %> > <%= task.status %></li>
  <% end %>
</ul>

<%= link_to '新規登録', new_task_path %>

app/views/tasks/new.html.erb
<h1>買うものを入力</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>買うもの詳細</h1>
<p><%= @task.content %> : <%= @task.status %></p>

<%= link_to '一覧へ戻る', tasks_path %>
<%= link_to '編集する', edit_task_path(@task) %>
<%= link_to '削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>